### ISSUE TITLE
Using agent.py for LedFx

### ISSUE THREAD

**Issue by Suspect-byte** [nitzanvolman/dancyPi-audio-reactive-led#6]
@nitzanvolman First of all thank you for the script. I am new to coding because I want a bias/ audio led strip with the RPi 4. I want to use LedFx for my smart home and I found this one. Instead that I am using the visualization.py I just start the agent.py with sudo and add the ip to LedFx. But as soon the LedFX gives data through agent.py I get an error. Maybe what I am doing with LedFx and dancyPi is just stupid but at least a try. The error is: `Traceback (most recent call last):
  File "/home/pi/dancyPi-audio-reactive-led/python/agent.py", line 65, in <module>
    pm = pixel_channel.recv()
  File "/home/pi/dancyPi-audio-reactive-led/python/comm.py", line 38, in recv
    pm = PixelsMessage.from_bytes(data)
  File "/home/pi/dancyPi-audio-reactive-led/python/comm.py", line 77, in from_bytes
    pixels += [(bts[i*3], bts[i*3+1], bts[i*3+2])]
IndexError: bytearray index out of range`

Can you help me? Or do you have another idea instead to use this. I have apa102, RPi 4 and hyperion running. Do you know another code so my leds will be audio reactive? Or can you fix the Indexerror? Thanks in advance!

**Comment by nitzanvolman** [comment]
this code base was a quick hack i put together forked from, naztronaut/dancyPi-audio-reactive-led. 
The idea is to have the visualistion run on a computer / device with a mic, and it then sends the data to agent.py running on the RPi driving the led strip. 

the internal protocol is completely made up and i don't think it will work with LedFX out of the box.

**Comment by Suspect-byte** [comment]
@nitzanvolman Do you have a solution or can you maybe help me where I should look? You are obviously more experienced than me so maybe you can head me to the right direction.

**Comment by nitzanvolman** [comment]
if we were to use the agent.py for this, it would need to use a different
protocol
LedFx uses a protocol called e1.31 https://opendmx.net/index.php/E1.31

alternatively you can use LedFX with a more appropriate project like:
https://github.com/scottlawsonbc/audio-reactive-led-strip
